
from nipype.pipeline import engine as pe
from nipype.interfaces import (
    utility as niu,
    freesurfer as fs,
    fsl,
    image,
)


from ..interfaces import workbench as wb

def init_hcp_segment_anat_wf(name='hcp_segment_anat_wf'):
    """
    This workflow generates WM, CSF and GM exclusion masks using the same 
    pipeline from the HCP pipeline.

    **Paramters**

        name
            Name for the workflow hierarchy of Niype

    **Inputs**
        wmparc
            gyral white matter segmentation generated by freesurfer warped 
            MNI space
        atlasroi
            vertex mask
        midthickness
            midthickness surface
        white
            white matter surface
        pial
            pial surface
        ROIs
            subcortical parcellation of brain warped into MNI space

    **Outputs**
        masks
            WM, CSF, and GM exclusion masks
    """
        
        
